### ISSUE TITLE
How do I create a hot key to remove all breakpoints in a file?

### ISSUE THREAD

**Issue by linzhiqiu** [obormot/PythonBreakpoints#14]

**Comment by obormot** [comment]
Sorry for the long reply, I haven't been working on this project anymore. Anyway, here it is:
(this is on a Mac) 
Preferences -> Package Settings -> Python Breakpoints -> Key Bindings (User) 
add 
```
{ "keys": ["your key combo"], "command": "clear_all_breakpoints" },
```
